<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>基于phalcon博客后台管理首页</title>
	<link rel="stylesheet" href="/back/css/admin.css" />
	<script type="text/javascript" src="/back/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/back/js/admin.js"></script>
<!-- 默认打开目标 -->
<base target="iframe"/>
</head>
<body>
<!-- 头部 -->
	<div id="top_box">
		<div id="top">
			<p id="top_font">博客后台管理首页 （V1.1）</p>
		</div>
		<div class="top_bar">
			<p class="adm">
				<span>管理员：</span>
				<span class="adm_pic">&nbsp&nbsp&nbsp&nbsp</span>
				<span class="adm_people">[<?=$this->session->get('auth')['username']?>]</span>
			</p>
			<p class="now_time">
				今天是：<?=date('Y.m.d',time())?>
				您的当前位置是：
				<span>首页</span>
			</p>
			<p class="out">
				<span class="out_bg">&nbsp&nbsp&nbsp&nbsp</span>&nbsp
				<a href="<?= $this->url->get('admin/login/logout');?>" target="_self">退出</a>
			</p>
		</div>
	</div>
<!-- 左侧菜单 -->
		<div id="left_box">
			<p class="use">常用菜单</p>
			<?php foreach($parentMenus as $parent){?>
				<div class="menu_box">
					<h2><?=$parent['title']?></h2>
					<div class="text">
					<?php foreach($childMenus as $child){
							if($child['parent_id']==$parent['id']){
					?>
						<ul class="con">
					        <li class="nav_u">
					        	<a href="/<?=$child['url']?>" class="pos"  ><?=$child['title']?></a>				        	
					        </li> 
					    </ul>
					<?php } }?>
					</div>
				</div>
			<?php }?>
		</div>
		<!-- 右侧 -->
		<div id="right">
			<iframe  frameboder="0" border="0" 	scrolling="yes" name="iframe" src="<?= $this->url->get('admin/index/copy')?>"></iframe>
		</div>
	<!-- 底部 -->
	<div id="foot_box">
		<div class="foot">
			<p>@Copyright © 2013-2015  All Rights Reserved. 京ICP备0000000号</p>
		</div>
	</div>

</body>
</html>
<!--[if IE 6]>
    <script type="text/javascript" src="./js/iepng.js"></script>
    <script type="text/javascript">
        DD_belatedPNG.fix('.adm_pic, #left_box .pos, .span_server, .span_people', 'background');
    </script>
<![endif]-->
