<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
		<link rel="stylesheet" href="/back/css/public.css" />
	<title></title>
</head>
<body>
	<form action="<?=$this->url->get('admin/menu/edit/'.$menu->id);?>" method="post">
		<table class="table">
			<tr >
				<td class="th" colspan="2">修改菜单</td>
			</tr>
			<tr>
				<td>菜单名称</td>
				<td><input type="text" name="title" value="<?=$menu->title?>"/></td>
			</tr>
			<tr>
				<td>url</td>
				<td><input type="text" name="url" value="<?=$menu->url?>"/></td>
			</tr>
			<tr>
				<td>排序</td>
				<td><input type="text" name="sort" value="<?=$menu->sort?>"/></td>
			</tr>
			<tr>
				<td>是否显示在主菜单</td>
				<td><input type="text" name="is_main" value="<?=$menu->is_main?>"/></td>
			</tr>
			<tr>
				<td>上级栏目</td>
				<td>
					<select  name="parent_id">
						<option value="0">请选择</option>
						<?php foreach($menus as $item){?>
						<option <?php if($item->id==$menu->parent_id){ echo "selected='selected'";}?> value="<?=$item->id?>"><?=$item->title?></option>
						<?php }?>
					</select>
				</td>
			</tr>
			
			<tr>
				<td colspan="2">
					<input type="hidden" name="id" value="<?=$menu->id?>"/>
					<input type="submit" value="修改" class="input_button"/>
					<input type="reset" class="input_button"/>
				</td>
			</tr>
		</table>
	</form>
</body>
</html>