<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
		<link rel="stylesheet" href="/back/css/public.css" />
	<title></title>
</head>
<body>
	<form action="<?=$this->url->get('admin/admin/edit/'.$admin->id)?>" method="post" enctype="multipart/form-data">
		<table class="table">
			<tr >
				<td class="th" colspan="2">修改管理员</td>
			</tr>
			<tr>
				<td>用户名</td>
				<td>
					<input type="text" name="username" class="title" value="<?=$admin->username?>"/>
				</td>
			</tr>
			<tr>
				<td>密码</td>
				<td><input type="password" name="passwd"/></td>
			</tr>
			<tr>
				<td>角色</td>
				<td>
					<?php foreach($roles as $role){?>
					<?=$role->name?><input  <?php if(in_array($role->id,$roleIds)){ echo "checked='checked'";}?> type="checkbox" name="ids[]" value="<?=$role->id?>"/>
					<?php }?>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<input type="submit" value="修改" class="input_button"/>
					<input type="reset" class="input_button"/>
				</td>
			</tr>
		</table>
	</form>
	<script type="text/javascript" src="/back/js/jquery-1.7.2.min.js"></script>
	<script  type="text/javascript" >
		$(":input[type=password]").val('');
	</script>
</body>
</html>