<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title></title>
	<link rel="stylesheet" href="/back/css/public.css" />
	<script type="text/javascript" src="/back/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/back/js/public.js"></script>	
</head>
<body>
	<table class="table">
		<tr>
				<?=$this->flashSession->output();?>
		</tr>
		<tr>
			<td class="th" colspan="10">管理员列表</td>
		</tr>
		<tr>
			<td class="tdLittle1">ID</td>
			<td>用户名</td>
			<td class="tdLtitle7">操作</td>
		</tr>
		<?php foreach($admins as $k=>$v){?>
		<tr>
			<td ><?=$v->id?></td>
			<td><?=$v->username?></td>
			<td>
				<a href="<?=$this->url->get('admin/admin/edit/'.$v->id)?>">[编辑]</a>
				<a href="<?=$this->url->get('admin/admin/del/'.$v->id)?>">[删除]</a>
			</td>
		</tr>
		<?php }?>
	</table>
	<div class="page">
		<?=$page?>
	</div>
</body>
</html>