<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>33333</title>
	<link rel="stylesheet" href="/back/css/public.css" />
	<script type="text/javascript" src="/back//js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/back/js/public.js"></script>	
</head>
<body>
	<table class="table">
		<tr>
			<td class="th" colspan="10">查看栏目</td>
		</tr>
		<tr>
			<th>CID</th>
			<th>栏目名称</th>
			<th>状态</th>
			<th>操作</th>
		</tr>
		<?php foreach ($category as $k=>$v){?>
		<tr>	
			<td><?=$k?></td>
			<td><a href=""><?=$v->cname?></a></td>
			<td><?=$v->isoff==1?"关闭":"开启"?></td>
			<td>
				<a href="<?=$this->url->get('category/edit')?>?id=<?=$v->cid?>">[编辑]</a>
				<a href="<?=$this->url->get('category/del')?>?id=<?=$v->cid?>" class="del">[删除]</a>
			</td>
		</tr>
		<?php }?>
	</table>
		<div class="page">
			<a href="">1</a>
		</div>
</body>
</html>