<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title></title>
	<link rel="stylesheet" href="/back/css/public.css" />
	<script type="text/javascript" src="/back/js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/back/js/public.js"></script>	
</head>
<body>
	<table class="table">
		<tr>
				<?=$this->flashSession->output();?>
		</tr>
		<tr>
			<td class="th" colspan="10">查看博文</td>
		</tr>
		<tr>
			<td class="tdLittle1">AID</td>
			<td>标题</td>
			<td class="tdLittle2">栏目名称</td>
			<td class="tdLtitle3">查看次数</td>
			<td class="tdLtitle4">创作时间</td>
			<td class="tdLtitle7">操作</td>
		</tr>
		<?php foreach($articles as $k=>$v){?>
		<tr>
			<td ><?=$v->aid?></td>
			<td><?=$v->title?></td>
			<td><a href=""><?=$v->cname?></a></td>
			<td><?=$v->click?></td>
			<td><?=date('Y-m-d',$v->time)?></td>
			<td>
				<a href="<?=$this->url->get('article/top')?>?id=<?=$v->aid?>">[置顶]</a>
				<a href="<?=$this->url->get('article/edit')?>?id=<?=$v->aid?>">[编辑]</a>
				<a href="<?=$this->url->get('article/del')?>?id=<?=$v->aid?>">[删除]</a>
			</td>
		</tr>
		<?php }?>
	</table>
	<div class="page">
		<?=$page?>
	</div>
</body>
</html>