<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
		<link rel="stylesheet" href="/back/css/public.css" />
	<title></title>
</head>
<body>
	<form action="<?=$this->url->get('admin/role/edit/'.$role->id)?>" method="post">
		<table class="table">
			<tr >
				<td class="th" colspan="2">分配权限</td>
			</tr>
			<tr>
				<td>角色名称</td>
				<td><input type="text" name="name" value="<?=$role->name?>"/></td>
			</tr>
			<tr>
				<td>角色描述</td>
				<td><input type="text" name="des" value="<?=$role->des?>"/></td>
			</tr>
			
			<tr>
				<td>权限列表</td>
			</tr>
				<?php foreach($parent as $item){
						if($item->level==0){
				?>
							<tr><td><?=$item->title?><input <?php if(in_array($item->id,$menuIds)){ echo "checked='checked'";}?> type="checkbox"  name="ids[]" value="<?=$item->id?>"/>
								<table>
									<tr>
										<?php foreach($children as $child){	
												if($child->parent_id==$item->id){
										?>
											<td><?=$child->title?><input <?php if(in_array($item->id,$menuIds)){ echo "checked='checked'";}?> type="checkbox"  name="ids[]" value="<?=$child->id?>"/></td>
										<?php }}?>
									</tr>
								</table>
							</td></tr>
				<?php
				} }?>
			<tr>
				<td colspan="2">
					<input type="submit" value="修改" class="input_button"/>
					<input type="reset" class="input_button"/>
				</td>
			</tr>
		</table>
	</form>
</body>
</html>