<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title>33333</title>
	<link rel="stylesheet" href="/back/css/public.css" />
	<script type="text/javascript" src="/back//js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="/back/js/public.js"></script>	
</head>
<body>
	<table class="table">
		<tr>
			<td><?=$this->flashSession->output();?></td>
		</tr>
		<tr>
			<td class="th" colspan="10">角色列表</td>
		</tr>
		<tr>
			<th>id</th>
			<th>角色名字</th>
			<th>角色描述</th>
			<th>操作</th>
		</tr>
		<?php foreach ($roles as $k=>$v){?>
		<tr>	
			<td><?=$v->id?></td>
			<td><a href=""><?=$v->name?></a></td>
			<td><?=$v->des?></td>
			<td>
				<a href="<?=$this->url->get('admin/role/edit/'.$v->id)?>">[权限分配]</a>
				<a href="<?=$this->url->get('admin/role/del/'.$v->id)?>" class="del">[删除]</a>
			</td>
		</tr>
		<?php }?>
	</table>
		<div class="page">
			<a href="">1</a>
		</div>
</body>
</html>